import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import {
	addCategoryItem,
	getAllCategoryItems,
	modifyCategoryItem,
	deleteCategoryItem,
	sortItems
} from "./categoryUtils";

const initialState = {
	status: "idle",
	categoryItems: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const addCategoryItemAsync = createAsyncThunk(
	"category/addCategoryItem",
	async (data) => {
		const resData = await addCategoryItem(data);
		// The value we return becomes the `fulfilled` action payload
		return resData;
	}
);

export const getAllCategoryItemsAsync = createAsyncThunk(
	"category/getAllCategoryItems",
	async (data) => {
		const resData = await getAllCategoryItems(data);
		// The value we return becomes the `fulfilled` action payload
		return resData;
	}
);

export const modifyCategoryItemAsync = createAsyncThunk(
	"category/modifyCategoryItem",
	async (data) => {
		const resData = await modifyCategoryItem(data);
		// The value we return becomes the `fulfilled` action payload
		return resData;
	}
);

export const deleteCategoryItemAsync = createAsyncThunk(
	"category/deleteCategoryItem",
	async (data) => {
		const resData = await deleteCategoryItem(data);
		// The value we return becomes the `fulfilled` action payload
		return resData;
	}
);

export const categorySlice = createSlice({
	name: "category",
	initialState,
	// The `reducers` field lets us define reducers and generate associated actions
	reducers: {
		addCategoryItemSync: (state, action) => {
			const item = action.payload;
			state.categoryItems = [item].concat(state.categoryItems);
		},
		modifyCategoryItemSync: (state, action) => {
			const item = action.payload;
			state.categoryItems = state.categoryItems.map((categoryItem) =>
				categoryItem._id === item._id ? item : categoryItem
			);
		},
		deleteCategoryItemSync: (state, action) => {
			const item = action.payload;
			state.categoryItems = state.categoryItems.filter(
				(categoryItem) => categoryItem._id !== item._id
			);
		},
		resetCategoryData: (state)=>{
			state.status = "idle"
			state.categoryItems = []
		}
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: (builder) => {
		builder
			.addCase(addCategoryItemAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(addCategoryItemAsync.fulfilled, (state, action) => {
				const categoryData = JSON.parse(JSON.stringify(action.payload));
				state.status = "idle";
				state.categoryItems = [categoryData].concat(state.categoryItems);
			})
			.addCase(addCategoryItemAsync.rejected, (state) => {
				state.status = "error";
			})
			.addCase(getAllCategoryItemsAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(getAllCategoryItemsAsync.fulfilled, (state, action) => {
				const categoryData = JSON.parse(JSON.stringify(action.payload));
				state.status = "idle";
				state.categoryItems = categoryData.sort(sortItems);
			})
			.addCase(getAllCategoryItemsAsync.rejected, (state) => {
				state.status = "error";
			})
			.addCase(modifyCategoryItemAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(modifyCategoryItemAsync.fulfilled, (state, action) => {
				const categoryData = JSON.parse(JSON.stringify(action.payload));
				state.categoryItems = state.categoryItems.map((categoryItem) =>
					categoryItem._id === categoryData._id ? categoryData : categoryItem
				);
			})
			.addCase(modifyCategoryItemAsync.rejected, (state) => {
				state.status = "error";
			})
			.addCase(deleteCategoryItemAsync.pending, (state) => {
				state.status = "loading";
			})
			.addCase(deleteCategoryItemAsync.fulfilled, (state, action) => {
				const categoryData = JSON.parse(JSON.stringify(action.payload));
				state.status = "idle";
				state.categoryItems = state.categoryItems.filter(
					(categoryItem) => categoryItem._id !== categoryData._id
				);
			})
			.addCase(deleteCategoryItemAsync.rejected, (state, action) => {
				state.status = "error";
			});
	},
});

export const { addCategoryItemSync, modifyCategoryItemSync, deleteCategoryItemSync, resetCategoryData } = categorySlice.actions;

export default categorySlice.reducer;
