version: "3"
services:

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    # volumes: 
    #   - ./server/database/mongo:/data/db  # dev Mode
    networks:
      - backend

  todo_server:
    container_name: todo_server
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    # volumes: # Dev Mode
    #   - ./server/:/usr/src/app/ # Dev Mode
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    environment:
      WAIT_HOSTS: mongodb:27017
      WAIT_AFTER_HOSTS: 2
    command: sh -c "/wait && npm run start" # npm run dev" # Dev Mode

  todo_client:
    container_name: todo_client
    restart: always
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - todo_server
    networks:
      - frontend
    environment:
      WAIT_HOSTS: todo_server:5000
      WAIT_AFTER_HOSTS: 1
    stdin_open: true
    command: sh -c "/wait && nginx -g 'daemon off;'"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
